# Q-Learning

In [2]:
import numpy as np
import random

In [57]:
R_matrix = np.array([[0, 0, 0, -1, 0, 0, -1, 0, 0, 0],
                     [0, -1, -1, -1, 0, 0, 0, 0, -1, 0],
                     [0, 0, 0, 0, 0, 0, 0, 0, -1, 0],
                     [0, -1, 0, 0, -1, 0, 0, 0, -1, 0],
                     [0, -1, 0, 0, -1, -1, -1, -1, -1, 100],
                     [0, -1, 0, 0, 0, 0, 0, 0, -1, 0],
                     [0, -1, -1, -1, 0, 0, -1, 0, -1, 0],
                     [0, 0, 0, -1, 0, 0, -1, 0, 0, 0],
                     [0, 0, 0, 0, 0, 0, -1, 0, 0, 0]])

In [53]:
R_matrix = np.array([[0, -1, -1, 0],
                     [-1, 100, 0, -1],
                     [0, 100, -1, -1],
                     [-1, -1, 0, 0]])

In [53]:
learning_rate = 0.7
discount_factor = 0.95
exploration_prob = 0.2
epochs = 10000
n_states = len(R_matrix)
n_actions = 10
goal_state = 5

In [89]:
Q_matrix = R_matrix.copy()

In [90]:
R_matrix

array([[  0,  -1,  -1,   0],
       [ -1, 100,   0,  -1],
       [  0, 100,  -1,  -1],
       [ -1,  -1,   0,   0]])

In [91]:
Q_matrix

array([[  0,  -1,  -1,   0],
       [ -1, 100,   0,  -1],
       [  0, 100,  -1,  -1],
       [ -1,  -1,   0,   0]])

In [66]:
Q_matrix[2][1] = R_matrix[2][1] + learning_rate * max(Q_matrix[1])

In [69]:
Q_matrix[3][2] = R_matrix[3][2] + learning_rate * max(Q_matrix[2])

In [72]:
Q_matrix[3][3] = R_matrix[3][3] + learning_rate * max(Q_matrix[3])

In [75]:
Q_matrix[3][0] = R_matrix[3][0] + learning_rate * max(Q_matrix[0])

In [81]:
Q_matrix[0][3] = R_matrix[0][3] + learning_rate * max(Q_matrix[3])

In [83]:
Q_matrix[0][0] = R_matrix[0][0] + learning_rate * max(Q_matrix[0])

In [85]:
Q_matrix[2][0] = R_matrix[2][0] + learning_rate * max(Q_matrix[0])

In [96]:
learning_rate = 0.7
n_states = len(R_matrix)
n_actions = len(R_matrix[0])
goal_state = 1
epochs = 100

In [97]:
for epoch in range(epochs):
    random_state = np.random.randint(0, n_states-1)
    random_action = np.random.randint(0, n_actions-1)
    while random_state != goal_state:
        if random_state == goal_state or Q_matrix[random_state][random_action] == -1:
            break
        else:
            Q_matrix[random_state, random_action] = R_matrix[random_state, random_action] + learning_rate * max(Q_matrix[random_action])
            random_state = random_action
            random_action = np.argmax(Q_matrix[random_state])
            if random_state == goal_state:
                break
    print(epoch)

0


KeyboardInterrupt: 

In [98]:
Q_matrix

array([[  0,  -1,  -1,   0],
       [ -1, 100,   0,  -1],
       [  0, 170,  -1,  -1],
       [ -1,  -1,   0,   0]])

In [58]:
for epoch in range(epochs):
    current_state = np.random.randint(0, n_states) # Start from a random state
    while current_state != goal_state:
        # Choose action with epsilon-greedy strategy
        if np.random.rand() < exploration_prob:
            action = np.random.randint(0, n_actions) # Choose a random direction to explore
        else:
            action = np.argmax(Q_matrix[current_state]) # Choose best action from current state

        # Move to the next state
        next_state = (current_state + 1) % n_states

        # Define a reward function
        reward = 1 if next_state == goal_state else 0

        # Update Q-value using the Q-learning update rule
        Q_matrix[current_state, action] += learning_rate * (reward + discount_factor * np.max(Q_matrix[next_state]) - Q_matrix[current_state, action])

        current_state = next_state # Move to the next state
        print(Q_matrix[current_state, action])

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [59]:
Q_matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 0, -1,  0,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])