# Q-Learning

In [1]:
import numpy as np
import random

In [4]:
np.zeros((4*4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
R = np.array([[0, 0, 0, -1, 0, 0, -1, 0, 0, 0],
                     [0, -1, -1, -1, 0, 0, 0, 0, -1, 0],
                     [0, 0, 0, 0, 0, 0, 0, 0, -1, 0],
                     [0, -1, 0, 0, -1, 0, 0, 0, -1, 0],
                     [0, -1, 0, 0, -1, -1, -1, -1, -1, 100],
                     [0, -1, 0, 0, 0, 0, 0, 0, -1, 0],
                     [0, -1, -1, -1, 0, 0, -1, 0, -1, 0],
                     [0, 0, 0, -1, 0, 0, -1, 0, 0, 0],
                     [0, 0, 0, 0, 0, 0, -1, 0, 0, 0]])

In [43]:
alpha = 0.7
gamma = 0.95
max_epsilon = 1.0
min_epsilon = 0.05
decay_rate = 0.0005
epochs = 1000
actions = ['up', 'down', 'left', 'right']
x = len(R)
y = len(R[0])
states = x*y
Q = np.zeros((x*y, 4))
max_steps = 200
goal_state = 49

In [44]:
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [45]:
state = 0
walls = []

for i in range(x):
    for j in range(y):
        if R[i][j] == -1:
            walls.append(state)
            for a in range(len(actions)):
                Q[state][a] = -50
        state += 1

state = 0

for i in range(x):
    for j in range(y):
        if i == 0 or state - 10 in walls:
            Q[state][actions.index('up')] = -50
        if i == x - 1 or state + 10 in walls:
            Q[state][actions.index('down')] = -50
        if j == 0 or state - 1 in walls:
            Q[state][actions.index('left')] = -50
        if j == y - 1 or state + 1 in walls:
            Q[state][actions.index('right')] = -50
        state += 1

In [46]:
Q

array([[-50.,   0., -50.,   0.],
       [-50., -50.,   0.,   0.],
       [-50., -50.,   0., -50.],
       [-50., -50., -50., -50.],
       [-50.,   0., -50.,   0.],
       [-50.,   0.,   0., -50.],
       [-50., -50., -50., -50.],
       [-50.,   0., -50.,   0.],
       [-50., -50.,   0.,   0.],
       [-50.,   0.,   0., -50.],
       [  0.,   0., -50., -50.],
       [-50., -50., -50., -50.],
       [-50., -50., -50., -50.],
       [-50., -50., -50., -50.],
       [  0.,   0., -50.,   0.],
       [  0.,   0.,   0.,   0.],
       [-50.,   0.,   0.,   0.],
       [  0.,   0.,   0., -50.],
       [-50., -50., -50., -50.],
       [  0.,   0., -50., -50.],
       [  0.,   0., -50.,   0.],
       [-50., -50.,   0.,   0.],
       [-50.,   0.,   0.,   0.],
       [-50.,   0.,   0.,   0.],
       [  0., -50.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -50.],
       [-50., -50., -50., -50.],
       [  0.,   0., -50., -50.],
       [  

In [37]:
def get_epsilon(epoch):
    return min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * epoch)

In [42]:
def take_action(random_state, epsilon):
    indexes = [index for index,value in enumerate(Q[random_state]) if value != -50]
    possible_actions = [value for index,value in enumerate(actions) if index in indexes]
    if np.random.random() > epsilon:
        if np.max(Q[random_state]) == -50:
            return None
        else:
            return actions[np.argmax(Q[random_state])]
    else:    
        return random.choice(possible_actions)

In [39]:
def update_table(state, action, reward, next_state):
    """
    Update Q table
    """
    Q[state][actions.index(action)] += alpha * (reward + gamma * np.max(Q[next_state]))

In [47]:
possible_states = [x for x in range(len(Q)) if x not in walls]
for epoch in range(epochs):
    random_state = random.choice(possible_states)
    epsilon = get_epsilon(epoch)
    for steps in range(max_steps):
        action = take_action(random_state, epsilon)
        if action == None:
            break
        elif action == 'up':
            next_state = random_state - 10
        elif action == 'down':
            next_state = random_state + 10
        elif action == 'left':
            next_state = random_state - 1
        elif action == 'right':
            next_state = random_state + 1
        if random_state != goal_state:
            reward = -1
        elif random_state == goal_state:
            reward = 1
            break
        #print(f"Epoch: {epoch}, steps: {steps}, random state: {random_state}, next state: {next_state}")
        update_table(random_state, action, reward, next_state)
        random_state = next_state

Epoch: 0, steps: 0, random state: 24, next state: 23
Epoch: 0, steps: 1, random state: 23, next state: 22
Epoch: 0, steps: 2, random state: 22, next state: 23
Epoch: 0, steps: 3, random state: 23, next state: 33
Epoch: 0, steps: 4, random state: 33, next state: 43
Epoch: 0, steps: 5, random state: 43, next state: 33
Epoch: 0, steps: 6, random state: 33, next state: 23
Epoch: 0, steps: 7, random state: 23, next state: 24
Epoch: 0, steps: 8, random state: 24, next state: 25
Epoch: 0, steps: 9, random state: 25, next state: 35
Epoch: 0, steps: 10, random state: 35, next state: 36
Epoch: 0, steps: 11, random state: 36, next state: 26
Epoch: 0, steps: 12, random state: 26, next state: 16
Epoch: 0, steps: 13, random state: 16, next state: 15
Epoch: 0, steps: 14, random state: 15, next state: 14
Epoch: 0, steps: 15, random state: 14, next state: 15
Epoch: 0, steps: 16, random state: 15, next state: 16
Epoch: 0, steps: 17, random state: 16, next state: 15
Epoch: 0, steps: 18, random state: 15,

In [41]:
Q

array([[-5.00000000e+01, -3.22675617e+03, -5.00000000e+01,
        -2.80489276e+03],
       [-5.00000000e+01, -5.00000000e+01, -3.04981069e+03,
        -3.38600721e+03],
       [-5.00000000e+01, -5.00000000e+01, -3.49969319e+03,
        -5.00000000e+01],
       [-5.00000000e+01, -5.00000000e+01, -5.00000000e+01,
        -5.00000000e+01],
       [-5.00000000e+01, -1.94419860e+03, -5.00000000e+01,
        -1.81888933e+03],
       [-5.00000000e+01, -2.90153129e+04, -2.00755024e+03,
        -5.00000000e+01],
       [-5.00000000e+01, -5.00000000e+01, -5.00000000e+01,
        -5.00000000e+01],
       [-5.00000000e+01, -2.36398790e+03, -5.00000000e+01,
        -1.49219795e+03],
       [-5.00000000e+01, -5.00000000e+01, -1.61282246e+03,
        -1.17777627e+03],
       [-5.00000000e+01, -1.41641615e+03, -1.24622949e+03,
        -5.00000000e+01],
       [-2.78481421e+03, -2.93172656e+03, -5.00000000e+01,
        -5.00000000e+01],
       [-5.00000000e+01, -5.00000000e+01, -5.00000000e+01,
      